name: dry-effects
codacy_id: 158a8a584a3845eba4a67a71ad540210
gemspec:
  authors: ["Nikita Shilnikov"]
  email: ["fg@flashgordon.ru"]
  summary: "Algebraic effects"
  development_dependencies:
    - bundler
    - rake
    - rspec
  runtime_dependencies:
    - [zeitwerk, "~> 2.6"]
    - [concurrent-ruby, "~> 1.0"]
    - [dry-core, "~> 1.0"]
    - [dry-inflector, "~> 1.0"]
    - [dry-initializer, "~> 3.0"]
