name: dry-effects
codacy_id: 158a8a584a3845eba4a67a71ad540210
gemspec:
  authors: ["Nikita Shilnikov"]
  email: ["fg@flashgordon.ru"]
  summary: "Algebraic effects"
  runtime_dependencies:
    - [zeitwerk, "~> 2.6"]
    - [concurrent-ruby, "~> 1.0"]
    - [dry-core, "~> 1.1"]
    - [dry-inflector, "~> 1.1"]
    - [dry-initializer, "~> 3.2"]
