name: dry-effects
codacy_id: 158a8a584a3845eba4a67a71ad540210
gemspec:
  authors: ["Nikita Shilnikov"]
  email: ["fg@flashgordon.ru"]
  summary: "Algebraic effects"
  development_dependencies:
    - bundler
    - rake
    - rspec
  runtime_dependencies:
    - [concurrent-ruby, "~> 1.0"]
    - [dry-configurable]
    - [dry-container, "~> 0.7", ">= 0.7.2"]
    - [dry-core, "~> 0.5", ">= 0.5"]
    - [dry-inflector, "~> 0.1", ">= 0.1.2"]
    - [dry-initializer, "~> 3.0"]
